### PR TITLE
Added contact info

### PR DESCRIPTION
**Pull request by tcnh**

### CODE REVIEW

**Comment by fhoeben** [comment]
Do you have a project to properly test whether this works (I only have a 'sample project')?
It would be good to see whether a true 1.0.0 release is warranted...

**Comment by tcnh** [comment]
I'll try this approach (maven profile) on one of the projects I use allure for reporting to see if the results are identical.

**Comment by fhoeben** [comment]
@tcnh does the listener work in your projects?

**Comment by tcnh** [comment]
@fhoeben I can confirm the listener works when used as described in the readme. Tried with one of my projects; no issues

**Pull request merged**
